//
//  OrganizationsMapShowRouter.swift
//  OmnieCommerce
//
//  Created by msm72 on 23.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OrganizationsMapShowRouterInput {
    func navigateToOrganizationShowScene(withOrganization organization: Organization)
}

class OrganizationsMapShowRouter: OrganizationsMapShowRouterInput {
    // MARK: - Properties
    weak var viewController: OrganizationsMapShowViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToOrganizationShowScene(withOrganization organization: Organization) {
        let storyboard                          =   UIStoryboard(name: "OrganizationShow", bundle: nil)
        let organizationShowVC                  =   storyboard.instantiateViewController(withIdentifier: "OrganizationShowVC") as! OrganizationShowViewController
        organizationShowVC.organization         =   organization
        
        viewController.navigationController?.pushViewController(organizationShowVC, animated: true)
    }
    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
