//
//  OrganizationShowPresenter.swift
//  OmnieCommerce
//
//  Created by msm72 on 26.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol OrganizationShowPresenterInput {
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol OrganizationShowPresenterOutput: class {
    func organizationDidShowLoad(fromViewModel: OrganizationShowModels.Organization.ViewModel)
}

class OrganizationShowPresenter: OrganizationShowPresenterInput {
    // MARK: - Properties
    weak var viewController: OrganizationShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func organizationDidShowLoad(fromViewModel: OrganizationShowModels.Organization.ViewModel) {
        
    }
}
