//
//  OrganizationShowRouter.swift
//  OmnieCommerce
//
//  Created by msm72 on 26.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OrganizationShowRouterInput {
    func navigateToOrganizationsMapShowScene(_ organization: Organization)
    func navigateToServiceShowScene(withID serviceID: String)
    func navigateToServicesShowScene(_ services: [Service])
}

class OrganizationShowRouter: OrganizationShowRouterInput {
    // MARK: - Properties
    weak var viewController: OrganizationShowViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToOrganizationsMapShowScene(_ organization: Organization) {
        let storyboard = UIStoryboard(name: "OrganizationsMapShow", bundle: nil)
        let organizationsMapShowVC = storyboard.instantiateViewController(withIdentifier: "OrganizationsMapShowVC") as! OrganizationsMapShowViewController
        organizationsMapShowVC.items = [organization]
        
        viewController.navigationController?.pushViewController(organizationsMapShowVC, animated: true)
    }

    func navigateToServiceShowScene(withID serviceID: String) {
        let storyboard = UIStoryboard(name: "ServiceShow", bundle: nil)
        let serviceShowVC = storyboard.instantiateViewController(withIdentifier: "ServiceShowVC") as! ServiceShowViewController
        serviceShowVC.serviceID = serviceID
        
        viewController.navigationController?.pushViewController(serviceShowVC, animated: true)        
    }

    func navigateToServicesShowScene(_ services: [Service]) {
        let storyboard = UIStoryboard(name: "ServicesShow", bundle: nil)
        let servicesShowVC = storyboard.instantiateViewController(withIdentifier: "ServicesShowVC") as! ServicesShowViewController
        servicesShowVC.services = services
        
        viewController.navigationController?.pushViewController(servicesShowVC, animated: true)
    }

    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
