//
//  OrdersShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SWRevealViewController
//import Localize_Swift

// MARK: - Input & Output protocols
protocol OrdersShowViewControllerInput {
    func displaySomething(viewModel: OrdersShow.Something.ViewModel)
}

protocol OrdersShowViewControllerOutput {
    func doSomething(request: OrdersShow.Something.Request)
}

class OrdersShowViewController: UIViewController, OrdersShowViewControllerInput {
    // MARK: - Properties
    var output: OrdersShowViewControllerOutput!
    var router: OrdersShowRouter!
    
    @IBOutlet weak var menuBarButton: UIBarButtonItem!
    @IBOutlet weak var ordersLabel: UILabel!
    

    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        OrdersShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // Localize Title
        //self.ordersLabel.text = "Молоко".localized()

        // Add Slide Menu actions
        if revealViewController() != nil {
            self.menuBarButton.target = revealViewController()
            self.menuBarButton.action = #selector(SWRevealViewController.revealToggle(_:))
            revealViewController().rightViewRevealWidth = 150
            
            view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
        }
        
        // NOTE: Ask the Interactor to do some work
        let request = OrdersShow.Something.Request()
        output.doSomething(request: request)
    }
    
    // Display logic
    func displaySomething(viewModel: OrdersShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
