//
//  OrdersShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension OrdersShowViewController: OrdersShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension OrdersShowInteractor: OrdersShowViewControllerOutput {
}

extension OrdersShowPresenter: OrdersShowInteractorOutput {
}

class OrdersShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = OrdersShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: OrdersShowViewController) {
        let router = OrdersShowRouter()
        router.viewController = viewController
        
        let presenter = OrdersShowPresenter()
        presenter.output = viewController
        
        let interactor = OrdersShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
