//
//  OrdersShowRouter.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OrdersShowRouterInput {
    func navigateToOrderShowScene(withOrderID orderID: String)
    func navigateToCalendar(withOrdersFromPeriod datesPeriod: DatesPeriod)
}

class OrdersShowRouter: OrdersShowRouterInput {
    // MARK: - Properties
    weak var viewController: OrdersShowViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToOrderShowScene(withOrderID orderID: String) {
        let storyboard = UIStoryboard(name: "OrderShow", bundle: nil)
        let orderShowVC = storyboard.instantiateViewController(withIdentifier: "OrderShowVC") as! OrderShowViewController
        orderShowVC.orderID = orderID
        orderShowVC.orderMode = .Preview
        
        viewController.navigationController?.pushViewController(orderShowVC, animated: true)
    }
    
    func navigateToCalendar(withOrdersFromPeriod datesPeriod: DatesPeriod) {
        let storyboard = UIStoryboard(name: "OrderCalendarShow", bundle: nil)
        let orderCalendarShowVC = storyboard.instantiateViewController(withIdentifier: "OrderCalendarShowVC") as! OrderCalendarShowViewController
        orderCalendarShowVC.ordersDatesPeriod = datesPeriod
        
        viewController.navigationController?.pushViewController(orderCalendarShowVC, animated: true)
        
        // Handler select new date completion
        orderCalendarShowVC.handlerSelectDatesPeriodCompletion = { datesPeriod in
            self.viewController.dateStart = (datesPeriod as! DatesPeriod).dateStart.convertToString(withStyle: .DateHyphen)
            self.viewController.dateEnd = (datesPeriod as! DatesPeriod).dateEnd.convertToString(withStyle: .DateHyphen)
            
            if (self.viewController.dateStart == self.viewController.dateEnd) {
                self.viewController.setupTitleLabel(withDate: (datesPeriod as! DatesPeriod).dateStart)
            } else {
                self.viewController.setupTitleLabel(withDatesPeriod: datesPeriod as! DatesPeriod)
            }
            
            self.viewController.viewSettingsDidLoad()
        }
    }

    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
