//
//  EnterCodeShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 07.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol EnterCodeShowInteractorInput {}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol EnterCodeShowInteractorOutput {}

class EnterCodeShowInteractor: EnterCodeShowInteractorInput {
    // MARK: - Properties
    var presenter: EnterCodeShowInteractorOutput!
    var worker: EnterCodeShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    /*
    func didValidateCode(fromRequestModel requestModel: EnterCodeShowModels.Code.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = EnterCodeShowWorker()
        let enterCode = requestModel.inputCode
        let isCodesEqual = worker.checkCodes(enterCode, andInputCode: requestModel.inputCode)
        
        // NOTE: Pass the result to the Presenter
        let responseModel = EnterCodeShowModels.Code.ResponseModel(isValueValid: isCodesEqual)
        presenter.didPrepareReturnValidationResult(fromResponseModel: responseModel)
    }
     */
}
