//
//  BusinessCardsShowPresenter.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol BusinessCardsShowPresenterInput {
    func presentSomething(response: BusinessCardsShow.Something.Response)
}

protocol BusinessCardsShowPresenterOutput: class {
    func displaySomething(viewModel: BusinessCardsShow.Something.ViewModel)
}

class BusinessCardsShowPresenter: BusinessCardsShowPresenterInput {
    // MARK: - Properties
    weak var output: BusinessCardsShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: BusinessCardsShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = BusinessCardsShow.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
