//
//  BusinessCardsShowInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol BusinessCardsShowInteractorInput {
    func businessCardsDidLoad(withRequestModel requestModel: BusinessCardsShowModels.Load.RequestModel)
}

protocol BusinessCardsShowInteractorOutput {
    func businessCardsDidPrepareToShowLoad(fromResponseModel responseModel: BusinessCardsShowModels.Load.ResponseModel)
}

class BusinessCardsShowInteractor: BusinessCardsShowInteractorInput {
    // MARK: - Properties
    var presenter: BusinessCardsShowInteractorOutput!
    var worker: BusinessCardsShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func businessCardsDidLoad(withRequestModel requestModel: BusinessCardsShowModels.Load.RequestModel) {
        // NOTE: Pass the result to the Presenter
        MSMRestApiManager.instance.userRequestDidRun(.userGetBusinessCardsList(requestModel.parameters, false), withHandlerResponseAPICompletion: { responseAPI in
            let businessCardsResponseModel = BusinessCardsShowModels.Load.ResponseModel(responseAPI: responseAPI)
            self.presenter.businessCardsDidPrepareToShowLoad(fromResponseModel: businessCardsResponseModel)
        })
    }
}
