//
//  HandbooksShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 20.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol HandbooksShowViewControllerInput {
    func displaySomething(viewModel: HandbooksShowModels.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol HandbooksShowViewControllerOutput {
    func doSomething(requestModel: HandbooksShowModels.Something.RequestModel)
}

class HandbooksShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: HandbooksShowViewControllerOutput!
    var router: HandbooksShowRouter!
    

    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        HandbooksShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    
    deinit {
        print(object: "\(self.className) deinit")
    }


    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        // Load data
        let requestModel    =   HandbooksShowModels.Something.RequestModel()
        interactor.doSomething(requestModel: requestModel)
    }
}


// MARK: - HandbooksShowViewControllerInput
extension HandbooksShowViewController: HandbooksShowViewControllerInput {
    func displaySomething(viewModel: HandbooksShowModels.Something.ViewModel) {
        // Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
