//
//  BusinessCardCreateInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 30.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol BusinessCardCreateInteractorInput {
    func doSomething(requestModel: BusinessCardCreateModels.Something.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol BusinessCardCreateInteractorOutput {
    func presentSomething(responseModel: BusinessCardCreateModels.Something.ResponseModel)
}

class BusinessCardCreateInteractor: BusinessCardCreateInteractorInput {
    // MARK: - Properties
    var presenter: BusinessCardCreateInteractorOutput!
    var worker: BusinessCardCreateWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(requestModel: BusinessCardCreateModels.Something.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = BusinessCardCreateWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let responseModel = BusinessCardCreateModels.Something.ResponseModel()
        presenter.presentSomething(responseModel: responseModel)
    }
}
