//
//  BusinessCardCreateViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 30.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol BusinessCardCreateViewControllerInput {
    func displaySomething(viewModel: BusinessCardCreateModels.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol BusinessCardCreateViewControllerOutput {
    func doSomething(requestModel: BusinessCardCreateModels.Something.RequestModel)
}

class BusinessCardCreateViewController: BaseViewController {
    // MARK: - Properties
    var interactor: BusinessCardCreateViewControllerOutput!
    var router: BusinessCardCreateRouter!
    
    var imageID: String?
    var businessCardID: String?


    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        BusinessCardCreateConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    

    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        // Load data
        let requestModel    =   BusinessCardCreateModels.Something.RequestModel()
        interactor.doSomething(requestModel: requestModel)
    }
}


// MARK: - BusinessCardCreateViewControllerInput
extension BusinessCardCreateViewController: BusinessCardCreateViewControllerInput {
    func displaySomething(viewModel: BusinessCardCreateModels.Something.ViewModel) {
        // Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
