//
//  FavoriteOrganizationsShowInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 28.03.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol FavoriteOrganizationsShowInteractorInput {
    func favoriteOrganizationsDidLoad(withRequestModel requestModel: FavoriteOrganizationsShowModels.Organizations.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol FavoriteOrganizationsShowInteractorOutput {
    func favoriteOrganizationsDidPrepareToShowLoad(fromResponseModel responseModel: FavoriteOrganizationsShowModels.Organizations.ResponseModel)
}

class FavoriteOrganizationsShowInteractor: FavoriteOrganizationsShowInteractorInput {
    // MARK: - Properties
    var presenter: FavoriteOrganizationsShowInteractorOutput!
    var worker: FavoriteOrganizationsShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func favoriteOrganizationsDidLoad(withRequestModel requestModel: FavoriteOrganizationsShowModels.Organizations.RequestModel) {
        MSMRestApiManager.instance.userRequestDidRun(.userGetFavoriteOrganizationsList(requestModel.parameters, true), withHandlerResponseAPICompletion: { responseAPI in
            let organizationsResponseModel = FavoriteOrganizationsShowModels.Organizations.ResponseModel(responseAPI: responseAPI, parameters: requestModel.parameters)
            self.presenter.favoriteOrganizationsDidPrepareToShowLoad(fromResponseModel: organizationsResponseModel)
        })
    }
}
