//
//  OnmieSoftShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension OnmieSoftShowViewController: OnmieSoftShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension OnmieSoftShowInteractor: OnmieSoftShowViewControllerOutput {
}

extension OnmieSoftShowPresenter: OnmieSoftShowInteractorOutput {
}

class OnmieSoftShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = OnmieSoftShowConfigurator()
    
    
    // MARK: - Class Initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: OnmieSoftShowViewController) {
        let router = OnmieSoftShowRouter()
        router.viewController = viewController
        
        let presenter = OnmieSoftShowPresenter()
        presenter.output = viewController
        
        let interactor = OnmieSoftShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
