//
//  NewsShowInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol NewsShowInteractorInput {
    func newsDidLoad(withRequestModel requestModel: NewsShowModels.NewsItems.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol NewsShowInteractorOutput {
    func newsDidPrepareToShow(fromResponseModel responseModel: NewsShowModels.NewsItems.ResponseModel)
}

class NewsShowInteractor: NewsShowInteractorInput {
    // MARK: - Properties
    var presenter: NewsShowInteractorOutput!
    var worker: NewsShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func newsDidLoad(withRequestModel requestModel: NewsShowModels.NewsItems.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker              =   NewsShowWorker()
        let items           =   worker.newsDidLoad()
        
        // NOTE: Pass the result to the Presenter
        let responseModel   =   NewsShowModels.NewsItems.ResponseModel(items: items)
        presenter.newsDidPrepareToShow(fromResponseModel: responseModel)
    }
}
