//
//  NewsShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol NewsShowViewControllerInput {
    func newsDidShow(fromViewModel viewModel: NewsShowModels.NewsItems.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol NewsShowViewControllerOutput {
    func newsDidLoad(withRequestModel requestModel: NewsShowModels.NewsItems.RequestModel)
}

class NewsShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: NewsShowViewControllerOutput!
    var router: NewsShowRouter!
    
    var tableViewControllerManager  =   TableViewControllerManager()
    
    @IBOutlet weak var smallTopBarView: SmallTopBarView!
    @IBOutlet weak var copyrightLabel: CustomLabel!
    @IBOutlet weak var segmentedControlView: SegmentedControlView!
    @IBOutlet weak var dataSourceEmptyView: UIView!

    @IBOutlet weak var tableView: CustomTableView! {
        didSet {
            // Register the Nib header/footer section views
            tableView.register(UINib(nibName: "NewsTableViewCell", bundle: nil), forCellReuseIdentifier: "NewsCell")
            
            // Delegates
            tableView.dataSource                            =   tableViewControllerManager
            tableView.delegate                              =   tableViewControllerManager
            tableViewControllerManager.tableView            =   tableView
            tableViewControllerManager.sourceType           =   .News
            
            smallTopBarView.searchBar.placeholder           =   "Enter Organization name".localized()

            // Handler select cell
            tableViewControllerManager.completionHandler    =   { organization in
                // TODO: ADD TRANSITION TO NEWS PROFILE
                self.print(object: "transition to News profile scene")
            }
        }
    }

    
    // MARK: - Class Initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        NewsShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
                
        // Config topBarView
        smallTopBarView.type    =   "ParentSearch"
        topBarViewStyle         =   .Small
        setup(topBarView: smallTopBarView)
        
        viewSettingsDidLoad()
    }
    

    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        print(object: "\(type(of: self)): \(#function) run.")
        
        setupSegmentedControlView()

        // NOTE: Ask the Interactor to do some work
        let requestModel        =   NewsShowModels.NewsItems.RequestModel()
        interactor.newsDidLoad(withRequestModel: requestModel)
    }
    
    func setupSegmentedControlView() {
        segmentedControlView.actionButtonHandlerCompletion = { sender in
            self.print(object: "\(type(of: self)): \(#function) run. Sender tag = \(sender.tag)")
            
        }
    }
    
    
    // MARK: - Transition
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        print(object: "\(type(of: self)): \(#function) run. New size = \(size)")
        
        smallTopBarView.setNeedsDisplay()
        smallTopBarView.circleView.setNeedsDisplay()
        segmentedControlView.setNeedsDisplay()
        _ = tableView.visibleCells.map{ ($0 as! BaseTableViewCell).dottedBorderView.setNeedsDisplay() }
    }
}


// MARK: - NewsShowViewControllerInput
extension NewsShowViewController: NewsShowViewControllerInput {
    func newsDidShow(fromViewModel viewModel: NewsShowModels.NewsItems.ViewModel) {
        guard (viewModel.news?.first?.count)! > 0 else {
            dataSourceEmptyView.isHidden    =   false

            return
        }
        
        self.tableViewControllerManager.sectionsCount   =   viewModel.news!.count
        self.tableViewControllerManager.dataSource      =   viewModel.news!.first!
        dataSourceEmptyView.isHidden                    =   true
        
        self.tableView.reloadData()
    }
}
