//
//  CategoriesShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol CategoriesShowViewControllerInput {
    func displaySomething(viewModel: CategoriesShow.Something.ViewModel)
}

protocol CategoriesShowViewControllerOutput {
    func doSomething(request: CategoriesShow.Something.Request)
}

class CategoriesShowViewController: BaseViewController, CategoriesShowViewControllerInput {
    // MARK: - Properties
    var output: CategoriesShowViewControllerOutput!
    var router: CategoriesShowRouter!
    
    @IBOutlet weak var topBarView: TopBarView!

    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        CategoriesShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
//        setup()

        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = CategoriesShow.Something.Request()
        output.doSomething(request: request)
    }
    
    // Display logic
    func displaySomething(viewModel: CategoriesShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
