//
//  CategoriesShowPresenter.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol CategoriesShowPresenterInput {
    func categoriesDidPrepareToShowLoad(fromResponseModel responseModel: CategoriesShowModels.Categories.ResponseModel)
    func citiesDidPrepareShowLoad(fromResponseModel responseModel: CategoriesShowModels.Cities.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol CategoriesShowPresenterOutput: class {
    func categoriesDidShowLoad(fromViewModel viewModel: CategoriesShowModels.Categories.ViewModel)
    func citiesDidShowLoad(fromViewModel viewModel: CategoriesShowModels.Cities.ViewModel)
}

class CategoriesShowPresenter: CategoriesShowPresenterInput {
    // MARK: - Properties
    weak var viewController: CategoriesShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func categoriesDidPrepareToShowLoad(fromResponseModel responseModel: CategoriesShowModels.Categories.ResponseModel) {
        // Save new data to CoreData
        let categories = responseModel.responseAPI?.body as? [Category]
        let entityCategories = CoreDataManager.instance.entityDidLoad(byName: keyCategories) as! Categories
        
        if  (categories != nil) {
            let categoriesData = NSKeyedArchiver.archivedData(withRootObject: categories!) as NSData?
            entityCategories.list = categoriesData!
        } else {
            entityCategories.list = nil
        }

        let categoriesViewModel = CategoriesShowModels.Categories.ViewModel(categories: categories)
        viewController.categoriesDidShowLoad(fromViewModel: categoriesViewModel)
    }
 
    func citiesDidPrepareShowLoad(fromResponseModel responseModel: CategoriesShowModels.Cities.ResponseModel) {
        let viewModel = CategoriesShowModels.Cities.ViewModel(list: responseModel.result)
        viewController.citiesDidShowLoad(fromViewModel: viewModel)
    }
}
