//
//  CategoriesShowWorker.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class CategoriesShowWorker {
    // MARK: - Custom Functions. Business Logic
    func dataSourceDidLoad() -> Array<Category> {
        var dataSource = [Category]()
        
        let names = [ "Auto Service", "Health", "Beauty", "Training", "Restaurants", "Tourism", "Sport" ]
        let images = [ "image-auto-service-normal", "image-health-normal", "image-beauty-normal", "image-training-normal", "image-restaurants-normal", "image-tourism-normal", "image-sport-normal" ]
        
        for i in 0 ..< names.count {
            dataSource.append(Category.init(names[i], images[i]))
        }

        return dataSource
    }
}
