//
//  CategoriesShowInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol CategoriesShowInteractorInput {
    func doSomething(request: CategoriesShow.Something.Request)
}

protocol CategoriesShowInteractorOutput {
    func presentSomething(response: CategoriesShow.Something.Response)
}

class CategoriesShowInteractor: CategoriesShowInteractorInput {
    // MARK: - Properties
    var output: CategoriesShowInteractorOutput!
    var worker: CategoriesShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(request: CategoriesShow.Something.Request) {
        // NOTE: Create some Worker to do the work
        worker = CategoriesShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let response = CategoriesShow.Something.Response()
        output.presentSomething(response: response)
    }
}
