//
//  MessagesShowWorker.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class MessagesShowWorker {
    // MARK: - Custom Functions. Business Logic
    func messagesDidLoad() -> [Message]? {
        guard arc4random_uniform(2) == 1 else {
            return nil
        }
        
        var items           =   [Message]()
        
        for index in 0 ..< 25 {
            let pathString  =   (arc4random_uniform(2) == 1) ? "http://www.nyhabitat.com/blog/wp-content/uploads/2013/08/fifth-avenue-shopping-manhattan-nyc-new-york.jpg" : nil
            
            let isOwn       =   (arc4random_uniform(2) == 1) ? true : false
            let avatar      =   (isOwn) ? "https://img08.rl0.ru/ee95eaba1d4a852f563dbcb3de9310a5/c1408x1636/img08.rl0.ru/cd011f2bc15d51a1b53a5b03a92defd0/c1408x1636/ilulill.ee/images/girlface.png" : "http://drawdoo.com/wp-content/themes/blogfolio/themify/img.php?src=http://drawdoo.com/wp-content/uploads/tutorials/Celebrities/lesson21/step_20.png&w=665&h=&zc=1&q=60&a=t"
            
            items.append(Message(name: "Акваторія-\(index)", logoStringURL: pathString, activeDate: Date.init(), text: "Вже давно відомо, що читабельний людині...", isOwn: isOwn, userAvatarStringURL: avatar, cellIdentifier: "MessageTableViewCell", cellHeight: 96.0))
        }
        
        return items
    }
}
