//
//  MessagesShowPresenter.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol MessagesShowPresenterInput {
    func presentSomething(response: MessagesShow.Something.Response)
}

protocol MessagesShowPresenterOutput: class {
    func displaySomething(viewModel: MessagesShow.Something.ViewModel)
}

class MessagesShowPresenter: MessagesShowPresenterInput {
    // MARK: - Properties
    weak var output: MessagesShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: MessagesShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = MessagesShow.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
