//
//  MessagesShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension MessagesShowViewController: MessagesShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension MessagesShowInteractor: MessagesShowViewControllerOutput {
}

extension MessagesShowPresenter: MessagesShowInteractorOutput {
}

class MessagesShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = MessagesShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: MessagesShowViewController) {
        let router = MessagesShowRouter()
        router.viewController = viewController
        
        let presenter = MessagesShowPresenter()
        presenter.output = viewController
        
        let interactor = MessagesShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
