//
//  BusinessCardShowWorker.swift
//  OmnieCommerce
//
//  Created by msm72 on 30.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class BusinessCardShowWorker {
    // MARK: - Custom Functions. Business Logic
    func doSomeWork() {
        // NOTE: Do the work
    }
}
