//
//  SignInContainerShowModels.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Data models
struct SignInContainerShowModels {
    struct User {
        struct RequestModel {
            let bodyParameters: [String: Any]
        }
        
        struct ResponseModel {
            let responseAPI: ResponseAPI?
        }
        
        struct ViewModel {
            let responseAPI: ResponseAPI?
        }
    }
}
