//
//  SlideMenuShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 09.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol SlideMenuShowViewControllerInput {
    func displaySomething(viewModel: SlideMenuShow.Something.ViewModel)
}

protocol SlideMenuShowViewControllerOutput {
    func doSomething(request: SlideMenuShow.Something.Request)
}

class SlideMenuShowViewController: UIViewController, SlideMenuShowViewControllerInput {
    // MARK: - Properties
    var output: SlideMenuShowViewControllerOutput!
    var router: SlideMenuShowRouter!
    
    @IBOutlet weak var tableView: UITableView!

    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        SlideMenuShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Delegates
        self.tableView.dataSource = self
        self.tableView.delegate = self
        
        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = SlideMenuShow.Something.Request()
        output.doSomething(request: request)
    }
    
    // Display logic
    func displaySomething(viewModel: SlideMenuShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}


// MARK: - UITableViewDataSource
extension SlideMenuShowViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MenuCell", for: indexPath) as! MenuViewCell
        
        cell.titleLabel.text = "Label \(indexPath.row)"
        
        return cell
    }
}


// MARK: - UITableViewDelegate
extension SlideMenuShowViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        switch indexPath.row {
        case 0:
            let ordersNC = UIStoryboard(name: "OrdersShow", bundle: nil).instantiateViewController(withIdentifier: "OrdersShowNC") as! BaseNavigationController            
            revealViewController().pushFrontViewController(ordersNC.viewControllers.first, animated: true)
            
        case 1:
            self.performSegue(withIdentifier: "MessagesShowSegue", sender: self)

        case 2:
            self.performSegue(withIdentifier: "FavoriteShowSegue", sender: self)

        case 3:
            self.performSegue(withIdentifier: "CategoriesShowSegue", sender: self)

        case 4:
            self.performSegue(withIdentifier: "NewsShowSegue", sender: self)

        default:
            self.performSegue(withIdentifier: "OrdersShowSegue", sender: self)

        }
    }
}


// 
