//
//  ServicesShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 14.04.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension ServicesShowViewController: ServicesShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ServicesShowInteractor: ServicesShowViewControllerOutput {
}

extension ServicesShowPresenter: ServicesShowInteractorOutput {
}

class ServicesShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = ServicesShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: ServicesShowViewController) {
        let router                  =   ServicesShowRouter()
        router.viewController       =   viewController
        
        let presenter               =   ServicesShowPresenter()
        presenter.viewController    =   viewController
        
        let interactor              =   ServicesShowInteractor()
        interactor.presenter        =   presenter
        
        viewController.interactor   =   interactor
        viewController.router       =   router
    }
}
