//
//  NewsActionsShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 31.03.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol NewsActionsShowViewControllerInput {
    func displaySomething(viewModel: NewsActionsShowModels.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol NewsActionsShowViewControllerOutput {
    func doSomething(requestModel: NewsActionsShowModels.Something.RequestModel)
}

class NewsActionsShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: NewsActionsShowViewControllerOutput!
    var router: NewsActionsShowRouter!

    @IBOutlet weak var tableView: MSMTableView!
    
    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        NewsActionsShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    

    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        // Load data
        let requestModel    =   NewsActionsShowModels.Something.RequestModel()
        interactor.doSomething(requestModel: requestModel)
    }
}


// MARK: - NewsActionsShowViewControllerInput
extension NewsActionsShowViewController: NewsActionsShowViewControllerInput {
    func displaySomething(viewModel: NewsActionsShowModels.Something.ViewModel) {
        // Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
