//
//  OmnieCardsShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OmnieCardsShowViewControllerInput {
    func omnieCardDidShowLoad(fromViewModel viewModel: OmnieCardsShowModels.Code.ViewModel)
}

protocol OmnieCardsShowViewControllerOutput {
    func omnieCardDidLoad(withRequestModel requestModel: OmnieCardsShowModels.Code.RequestModel)
}

class OmnieCardsShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: OmnieCardsShowViewControllerOutput!
    var router: OmnieCardsShowRouter!
    
    // IBOutlet
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var qrcodeImageView: UIImageView!
    @IBOutlet weak var barcodeImageView: UIImageView!
    @IBOutlet weak var smallTopBarView: SmallTopBarView!
    @IBOutlet weak var qrcodeLabel: UbuntuLightVeryLightGrayLabel!
    @IBOutlet weak var barcodeLabel: UbuntuLightVeryLightGrayLabel!

    
    // MARK: - Class Initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        OmnieCardsShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        viewSettingsDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
    }

    
    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        print(object: "\(type(of: self)): \(#function) run.")
        
        // Config smallTopBarView
        navigationBarView = smallTopBarView
        smallTopBarView.type = "Parent"
        haveMenuItem = true
        scrollViewBase = scrollView
     
        userOmnieCardDidLoad()
    }
    
    func userOmnieCardDidLoad() {
        spinnerDidStart(view)
        
        // Load data
        let omnieCardRequestModel = OmnieCardsShowModels.Code.RequestModel()
        interactor.omnieCardDidLoad(withRequestModel: omnieCardRequestModel)
    }
    
    func userOmnieCardDidShow() {
        // Generate Barcode Code
        if let image = Barcode.generateBarcodeFrom(stringCode: appUser.omniecardBarCode!, withImageSize: barcodeImageView.frame.size) {
            UIView.animate(withDuration: 0.5, animations: { 
                self.barcodeImageView.image = image
            })
        }

        if let image = Barcode.generateQRCodeFrom(stringCode: appUser.omniecardBarCode!, withImageSize: qrcodeImageView.frame.size) {
            UIView.animate(withDuration: 0.5, animations: {
                self.qrcodeImageView.image = image
            })
        }

        self.barcodeLabel.text = appUser.omniecardBarCode
        self.qrcodeLabel.text = appUser.omniecardBarCode

        spinnerDidFinish()
    }
    
    
    // MARK: - Transition
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        print(object: "\(type(of: self)): \(#function) run. New size = \(size)")
        
        smallTopBarView.setNeedsDisplay()
        smallTopBarView.circleView.setNeedsDisplay()
    }
}


// MARK: - OmnieCardsShowViewControllerInput
extension OmnieCardsShowViewController: OmnieCardsShowViewControllerInput {
    func omnieCardDidShowLoad(fromViewModel viewModel: OmnieCardsShowModels.Code.ViewModel) {
        // Check for errors
        guard viewModel.status == "SUCCESS" else {
            self.alertViewDidShow(withTitle: "Error", andMessage: viewModel.status, completion: {
                self.userOmnieCardDidShow()
            })
            
            return
        }
        
        userOmnieCardDidShow()
    }
}
