//
//  PersonalPageShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Toucan
import Kingfisher

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol PersonalPageShowViewControllerInput {
    func userAppDataDidShowLoad(fromViewModel viewModel: PersonalPageShowModels.LoadData.ViewModel)
    func userAppDataDidShowUpload(fromViewModel viewModel: PersonalPageShowModels.UploadData.ViewModel)
    func userAppImageDidShowUpload(fromViewModel viewModel: PersonalPageShowModels.UploadImage.ViewModel)
    func userAppImageDidShowDelete(fromViewModel viewModel: PersonalPageShowModels.LoadData.ViewModel)
    func userAppPasswordDidShowChange(fromViewModel viewModel: PersonalPageShowModels.UploadData.ViewModel)
    func userAppEmailDidShowChange(fromViewModel viewModel: PersonalPageShowModels.ChangeEmail.ViewModel)
    func userAppTemplatesDidShowLoad(fromViewModel viewModel: PersonalPageShowModels.Templates.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol PersonalPageShowViewControllerOutput {
    func userAppDataDidLoad(withRequestModel requestModel: PersonalPageShowModels.LoadData.RequestModel)
    func userAppDataDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadData.RequestModel)
    func userAppImageDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadImage.RequestModel)
    func userAppImageDidDelete(withRequestModel requestModel: PersonalPageShowModels.LoadData.RequestModel)
    func userAppPasswordDidChange(withRequestModel requestModel: PersonalPageShowModels.UploadData.RequestModel)
    func userAppEmailDidChange(withRequestModel requestModel: PersonalPageShowModels.ChangeEmail.RequestModel)
    func userAppTemplatesDidLoad(withRequestModel requestModel: PersonalPageShowModels.Templates.RequestModel)
}

class PersonalPageShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: PersonalPageShowViewControllerOutput!
    var router: PersonalPageShowRouter!

    // Container childVC
    var animationDirection: AnimationDirection?
    var personalDataVC: PersonalDataViewController?
    var personalTemplatesVC: PersonalTemplatesViewController?
    
    var wasImageUploaded: Bool?
    weak var avatarActionView: AvatarActionView?

    var activeViewController: BaseViewController? {
        didSet {
            guard oldValue != nil else {
                router.updateActiveViewController()
                
                return
            }
            
            animationDirection = ((oldValue?.view.tag)! < (activeViewController?.view.tag)!) ? .FromRightToLeft : .FromLeftToRight
            router.removeInactiveViewController(inactiveViewController: oldValue)
        }
    }
    
    // Outlets
    @IBOutlet weak var smallTopBarView: SmallTopBarView!
    @IBOutlet weak var copyrightLabel: CustomLabel!
    @IBOutlet weak var segmentedControlView: SegmentedControlView!
    @IBOutlet weak var containerView: CustomView!

    
    // MARK: - Class Initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        PersonalPageShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        spinnerDidStart(nil)
        
        // Config smallTopBarView
        navigationBarView = smallTopBarView
        smallTopBarView.type = "Parent"
        haveMenuItem = true
        
        viewSettingsDidLoad()
    }
    
    
    // MARK: - Custom Functions
    func viewSettingsDidLoad() {
        print(object: "\(type(of: self)): \(#function) run.")
        
        userAppDataDidLoad()
        setupSegmentedControlView()
        containerView.autoresizesSubviews = true
    }
    
    func personalDataDidShow() {
        // Container Child Views
        personalDataVC = UIStoryboard(name: "PersonalPageShow", bundle: nil).instantiateViewController(withIdentifier: "PersonalDataVC") as? PersonalDataViewController
        
        // Handler Avatar Button tap
        personalDataVC!.handlerPassDataCompletion = { sender in
            self.blackoutView = MSMBlackoutView.init(inView: self.view)
            
            self.blackoutView!.didShow()

            let avatarButton = sender as! CustomButton
            self.avatarActionView = AvatarActionView.init(inView: self.view)
            
            if ((sender as! CustomButton).currentImage == nil) {
                self.avatarActionView!.deleteButton.isHidden = true
            }
            
            // Handler AvatarActionView completions
            self.avatarActionView!.handlerViewDismissCompletion = { actionType in
                    switch actionType {
                    // Handler Photo Make button tap
                    case .PhotoUpload:
                        let imagePickerController = MSMImagePickerController()
                        imagePickerController.photoDidLoadFromAlbum()
                        
                        self.present(imagePickerController, animated: true, completion: nil)
                        
                        // Handler MSMImagePickerController results
                        self.handlerResult(fromImagePicker: imagePickerController, forAvatarButton: avatarButton)

                    case .PhotoMake:
                        let imagePickerController = MSMImagePickerController()
                        
                        guard imagePickerController.photoDidMakeWithCamera() else {
                            self.alertViewDidShow(withTitle: "Error", andMessage: "Camera is not available", completion: { _ in })
                            self.blackoutView!.didHide()
                            return
                        }
                        
                        self.present(imagePickerController, animated: true, completion: nil)

                        // Handler MSMImagePickerController results
                        self.handlerResult(fromImagePicker: imagePickerController, forAvatarButton: avatarButton)
                        
                    case .PhotoDelete:
                        UIView.animate(withDuration: 0.7, animations: {
                            avatarButton.setImage(UIImage.init(named: "image-no-user"), for: .normal)
                        }, completion: { success in
                            appUser.imageID = nil
                            CoreDataManager.instance.didSaveContext()
                            self.blackoutView!.didHide()
                        })
                    }
            }
            
                        
            // Handler AvatarActionView Cancel button tap
            self.avatarActionView!.handlerCancelButtonCompletion = { _ in
                self.blackoutView!.didHide()
            }
        }
        
        // Handler Action Buttons
        personalDataVC!.handlerSaveButtonCompletion = { parameters in
            guard isNetworkAvailable else {
                return
            }
            
            self.spinnerDidStart(nil)
            let uploadProfileRequestModel = PersonalPageShowModels.UploadData.RequestModel(parameters: parameters!)
            self.interactor.userAppDataDidUpload(withRequestModel: uploadProfileRequestModel)
        }
        
        personalDataVC!.handlerCancelButtonCompletion = { _ in
            self.router.navigateToNewsShowScene()
        }

        personalTemplatesVC = UIStoryboard(name: "PersonalPageShow", bundle: nil).instantiateViewController(withIdentifier: "PersonalTemplatesVC") as? PersonalTemplatesViewController
        
        // Handler Change Network State
        personalDataVC!.handlerChangeNetworkStateCompletion = { success in
            guard self.wasImageUploaded != nil else {
                return
            }
            
            if ((success as! Bool) && !self.wasImageUploaded!) {
                // Deferred Upload Image API
                self.spinnerDidStart(self.blackoutView!)
                let uploadedImage = (self.personalDataVC!.avatarButton.image(for: .normal))!
                let imageUploadRequestModel = PersonalPageShowModels.UploadImage.RequestModel(image: uploadedImage)
                self.interactor.userAppImageDidUpload(withRequestModel: imageUploadRequestModel)
            }
        }
        
        // Handler Change Email Button Tap
        personalDataVC!.handlerChangeEmailCompletion = { newEmail in
            let emailChangeRequestModel = PersonalPageShowModels.ChangeEmail.RequestModel(email: newEmail as! String)
            self.interactor.userAppEmailDidChange(withRequestModel: emailChangeRequestModel)
        }
    }
    
    func setupSegmentedControlView() {
        segmentedControlView.actionButtonHandlerCompletion = { sender in
            switch sender.tag {
            case 1:
                self.activeViewController = self.personalTemplatesVC
                
            default:
                self.activeViewController = self.personalDataVC
            }
        }
    }
    
    func userAppDataDidLoad() {
        if (isNetworkAvailable) {
            let loadRequestModel = PersonalPageShowModels.LoadData.RequestModel()
            self.interactor.userAppDataDidLoad(withRequestModel: loadRequestModel)
        } else {
            spinnerDidFinish()
            activeViewController = personalDataVC
        }
    }
    
    func handlerResult(fromImagePicker imagePickerController: MSMImagePickerController, forAvatarButton avatarButton: CustomButton) {
        // Handler Success Select Image
        imagePickerController.handlerImagePickerControllerCompletion = { image in
            let uploadedImage = Toucan(image: image)
                                .resize(avatarButton.frame.size, fitMode: Toucan.Resize.FitMode.crop)
                                .maskWithEllipse().image

            if (isNetworkAvailable) {
                // Upload Image API
                self.spinnerDidStart(self.blackoutView!)
                
                let imageUploadRequestModel = PersonalPageShowModels.UploadImage.RequestModel(image: image)
                self.interactor.userAppImageDidUpload(withRequestModel: imageUploadRequestModel)
            }
        }
        
        // Handler Cancel result
        imagePickerController.handlerCancelButtonCompletion = { _ in
            self.blackoutView!.didHide()
        }
    }
        
    
    // MARK: - Transition
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        smallTopBarView.setNeedsDisplay()
        smallTopBarView.circleView.setNeedsDisplay()
        segmentedControlView.setNeedsDisplay()
        
        if (self.activeViewController == self.personalTemplatesVC) {
            _ = self.personalTemplatesVC!.tableView.visibleCells.map{ ($0 as! UserTemplateTableViewCell).dottedBorderView.setNeedsDisplay() }
        }
    }
}


// MARK: - PersonalPageShowViewControllerInput
extension PersonalPageShowViewController: PersonalPageShowViewControllerInput {
    func userAppDataDidShowLoad(fromViewModel viewModel: PersonalPageShowModels.LoadData.ViewModel) {
        spinnerDidFinish()

        // Check Network state
        guard isNetworkAvailable else {
            activeViewController = personalDataVC

            return
        }
        
        // Check Response value
        guard viewModel.responseAPI != nil && (viewModel.responseAPI?.code == 200 || viewModel.responseAPI?.code == 2201) else {
            activeViewController = personalDataVC

            return
        }
        
        // Mofidy AppUser properties
        appUser.profileDidUpload(json: viewModel.responseAPI!.body as! [String: AnyObject])
        CoreDataManager.instance.didSaveContext()
        
        personalDataDidShow()
        activeViewController = personalDataVC

        // Get Templates
        let templatesRequestModel = PersonalPageShowModels.Templates.RequestModel(userID: "01") // self.userApp!.codeID!)
        self.interactor.userAppTemplatesDidLoad(withRequestModel: templatesRequestModel)
    }
    
    func userAppDataDidShowUpload(fromViewModel viewModel: PersonalPageShowModels.UploadData.ViewModel) {
        spinnerDidFinish()

        // Check for errors
        guard viewModel.status == "SUCCESS" else {
            self.alertViewDidShow(withTitle: "Error", andMessage: viewModel.status, completion: { })
            
            return
        }

        // Check Network state
        guard isNetworkAvailable else {
            activeViewController = personalDataVC
            return
        }
        
        CoreDataManager.instance.didSaveContext()
        router.navigateToNewsShowScene()
        
        if (viewModel.passwordsParams != nil) {
            let passwordChangeRequestModel = PersonalPageShowModels.UploadData.RequestModel(parameters: viewModel.passwordsParams!)
            interactor.userAppPasswordDidChange(withRequestModel: passwordChangeRequestModel)
        }
    }
    
    func userAppImageDidShowUpload(fromViewModel viewModel: PersonalPageShowModels.UploadImage.ViewModel) {
        spinnerDidFinish()
        
        // Check for errors
        guard viewModel.status == "SUCCESS" else {
            self.alertViewDidShow(withTitle: "Error", andMessage: viewModel.status, completion: { })
            
            return
        }

        // Check Network state
        guard isNetworkAvailable else {
            wasImageUploaded = false
            blackoutView!.didHide()
            return
        }
        
        CoreDataManager.instance.didSaveContext()
        ImageCache.default.store(personalDataVC!.avatarButton.image(for: .normal)!, forKey: "userImage")
        wasImageUploaded = true
        
        // Change Avatar Button Image
        if let imageID = appUser.imageID {
            self.personalDataVC?.avatarButton.kf.setImage(with: ImageResource(downloadURL: imageID.convertToURL(withSize: .Small, inMode: .Get), cacheKey: imageID), for: .normal,
                                                          placeholder: UIImage.init(named: "image-no-user"),
                                                          options: [.transition(ImageTransition.fade(1)),
                                                                    .processor(ResizingImageProcessor(referenceSize: (self.personalDataVC?.avatarButton.frame.size)!,
                                                                                                      mode: .aspectFill))],
                                                          completionHandler: { image, error, cacheType, imageURL in
                                                            self.personalDataVC?.avatarButton.imageView?.kf.cancelDownloadTask()
            })
        } else {
            self.personalDataVC!.avatarButton.setImage(UIImage.init(named: "image-no-user"), for: .normal)
        }
        
        self.blackoutView!.didHide()
    }
    
    func userAppPasswordDidShowChange(fromViewModel viewModel: PersonalPageShowModels.UploadData.ViewModel) {
        spinnerDidFinish()
        
        // Check for errors
        guard viewModel.status == "SUCCESS" else {
            self.alertViewDidShow(withTitle: "Error", andMessage: viewModel.status, completion: { })
            
            return
        }
    }

    func userAppEmailDidShowChange(fromViewModel viewModel: PersonalPageShowModels.ChangeEmail.ViewModel) {
        spinnerDidFinish()
        
        // Check Network state
        guard isNetworkAvailable else {
            self.wasImageUploaded = false
            return
        }
        
        guard viewModel.responseAPI?.code == 200 else {
            alertViewDidShow(withTitle: "Error", andMessage: (viewModel.responseAPI?.code == 3894) ? "3894 - Email use" : "Change Email error message", completion: { _ in })
            return
        }
        
        alertViewDidShow(withTitle: "Info", andMessage: "Change Email info message", completion: { _ in
            CoreDataManager.instance.didSaveContext()
            _ = self.personalDataVC!.textFieldsCollection.map({ $0.resignFirstResponder()})
            self.personalDataVC!.handlerChangeEmailButtonTap(self.personalDataVC!.emailChangeButton)
        })
    }
    
    func userAppImageDidShowDelete(fromViewModel viewModel: PersonalPageShowModels.LoadData.ViewModel) {
        spinnerDidFinish()
        
        // Check Network state
        guard isNetworkAvailable else {
            return
        }
        
        CoreDataManager.instance.didSaveContext()
        ImageCache.default.clearDiskCache()
        ImageCache.default.clearMemoryCache()
        self.personalDataVC!.avatarButton.setImage(UIImage.init(named: "image-no-user")!, for: .normal)
        self.blackoutView!.didHide()
    }
    
    func userAppTemplatesDidShowLoad(fromViewModel viewModel: PersonalPageShowModels.Templates.ViewModel) {
        spinnerDidFinish()
        
        guard isNetworkAvailable else {
            return
        }
        
        personalTemplatesVC!.organizations = viewModel.organizations!
    }
}
