//
//  PersonalPageShowModels.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Data models
struct PersonalPageShowModels {
    struct Data {
        struct RequestModel {
        }
        
        struct ResponseModel {
            let response: ResponseAPI?
        }
        
        struct ViewModel {
            let response: ResponseAPI?
        }
    }

    struct Templates {
        struct RequestModel {
            let userID: String
        }
        
        struct ResponseModel {
            let items: [Organization]?
        }
        
        struct ViewModel {
            let organizations: [Organization]?
        }
    }
}
