//
//  PersonalPageShowInteractor.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol PersonalPageShowInteractorInput {
    func userAppDataDidLoad(withRequestModel requestModel: PersonalPageShowModels.LoadData.RequestModel)
    func userAppDataDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadData.RequestModel)
    func userAppImageDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadImage.RequestModel)
    func userAppTemplatesDidLoad(withRequestModel requestModel: PersonalPageShowModels.Templates.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol PersonalPageShowInteractorOutput {
    func userAppDataDidPrepareToShowLoad(fromResponseModel responseModel: PersonalPageShowModels.LoadData.ResponseModel)
    func userAppDataDidPrepareToShowUpload(fromResponseModel responseModel: PersonalPageShowModels.UploadData.ResponseModel)
    func userAppImageDidPrepareToShowUpload(fromResponseModel responseModel: PersonalPageShowModels.UploadImage.ResponseModel)
    func userAppTemplatesDidPrepareToShowLoad(fromResponseModel responseModel: PersonalPageShowModels.Templates.ResponseModel)
}

class PersonalPageShowInteractor: PersonalPageShowInteractorInput {
    // MARK: - Properties
    var presenter: PersonalPageShowInteractorOutput!
    var worker: PersonalPageShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func userAppDataDidLoad(withRequestModel requestModel: PersonalPageShowModels.LoadData.RequestModel) {
        UIApplication.shared.isNetworkActivityIndicatorVisible = true
        
        MSMRestApiManager.instance.userGetProfileData { responseAPI in
            // Pass the result to the Presenter
            let loadResponseModel = PersonalPageShowModels.LoadData.ResponseModel(response: responseAPI)
            self.presenter.userAppDataDidPrepareToShowLoad(fromResponseModel: loadResponseModel)
        }
    }
    
    func userAppDataDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadData.RequestModel) {
//        worker              =   PersonalPageShowWorker()
//        let userApp         =   worker.userAppDidUpdateOnServer(withParameters: requestModel.params)
//        
//        // NOTE: Pass the result to the Presenter
//        let responseModel   =   PersonalPageShowModels.UserApp.ResponseModel(userApp: userApp)
//        presenter.userAppDataDidPrepareToShow(fromResponseModel: responseModel)
    }
    
    func userAppImageDidUpload(withRequestModel requestModel: PersonalPageShowModels.UploadImage.RequestModel) {
        UIApplication.shared.isNetworkActivityIndicatorVisible = true
        
        MSMRestApiManager.instance.userUploadImage(requestModel.image) { responseAPI in
            // Pass the result to the Presenter
            let imageUploadResponseModel = PersonalPageShowModels.UploadImage.ResponseModel(response: responseAPI)
            self.presenter.userAppImageDidPrepareToShowUpload(fromResponseModel: imageUploadResponseModel)
        }
    }

    func userAppTemplatesDidLoad(withRequestModel requestModel: PersonalPageShowModels.Templates.RequestModel) {
        worker = PersonalPageShowWorker()
        let items = worker.userAppTemplatesDidLoad(forUserApp: requestModel.userID)
        
        // Pass the result to the Presenter
        let responseModel = PersonalPageShowModels.Templates.ResponseModel(items: items)
        presenter.userAppTemplatesDidPrepareToShowLoad(fromResponseModel: responseModel)
    }
}
