//
//  HandbookShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension HandbookShowViewController: HandbookShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension HandbookShowInteractor: HandbookShowViewControllerOutput {
}

extension HandbookShowPresenter: HandbookShowInteractorOutput {
}

class HandbookShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = HandbookShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: HandbookShowViewController) {
        let router = HandbookShowRouter()
        router.viewController = viewController
        
        let presenter = HandbookShowPresenter()
        presenter.output = viewController
        
        let interactor = HandbookShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
