//
//  ServiceShowConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 24.04.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension ServiceShowViewController: ServiceShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ServiceShowInteractor: ServiceShowViewControllerOutput {
}

extension ServiceShowPresenter: ServiceShowInteractorOutput {
}

class ServiceShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = ServiceShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: ServiceShowViewController) {
        let router                  =   ServiceShowRouter()
        router.viewController       =   viewController
        
        let presenter               =   ServiceShowPresenter()
        presenter.viewController    =   viewController
        
        let interactor              =   ServiceShowInteractor()
        interactor.presenter        =   presenter
        
        viewController.interactor   =   interactor
        viewController.router       =   router
    }
}
