//
//  AboutShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol AboutShowViewControllerInput {
    func displaySomething(viewModel: AboutShow.Something.ViewModel)
}

protocol AboutShowViewControllerOutput {
    func doSomething(request: AboutShow.Something.Request)
}

class AboutShowViewController: BaseViewController, AboutShowViewControllerInput {
    // MARK: - Properties
    var output: AboutShowViewControllerOutput!
    var router: AboutShowRouter!
    
    @IBOutlet weak var aboutTopBarView: TopBarView!
    @IBOutlet weak var titleLabel: CustomLabel!
    @IBOutlet weak var menuButton: UIButton!

 
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        AboutShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setup(withTitle: "About")
        titleLabel.text = self.titleText
        titleLabel.setup(withType: .title)
        
        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = AboutShow.Something.Request()
        output.doSomething(request: request)
    }
    
    // Display logic
    func displaySomething(viewModel: AboutShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
