//
//  AboutShowViewController.swift
//  OmnieCommerce
//
//  Created by msm72 on 15.11.16.
//  Copyright (c) 2016 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol AboutShowViewControllerInput {
    func displaySomething(viewModel: AboutShow.Something.ViewModel)
}

protocol AboutShowViewControllerOutput {
    func doSomething(request: AboutShow.Something.Request)
}

class AboutShowViewController: BaseViewController, AboutShowViewControllerInput {
    // MARK: - Properties
    var output: AboutShowViewControllerOutput!
    var router: AboutShowRouter!
    
    @IBOutlet weak var smallTopBarView: SmallTopBarView!
    @IBOutlet weak var copyrightLabel: CustomLabel!
    @IBOutlet weak var topBarViewHeightPortraitConstraint: NSLayoutConstraint!
    
//    override var topBarViewRounding: String {
//        willSet {
//            if (newValue == "Big") {
//                topBarViewHeightPortraitConstraint.constant = Config.Constants.topViewBarHeightBig
//            }
//        }
//    }
    
 
    // MARK: - Class Initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        AboutShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Config topBarView
//        topBarViewRounding = "Big"
        setup(topBarView: smallTopBarView)
        
        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = AboutShow.Something.Request()
        output.doSomething(request: request)
    }
    
    // Display logic
    func displaySomething(viewModel: AboutShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
