//
//  DiscountCardCreateRouter.swift
//  OmnieCommerce
//
//  Created by msm72 on 24.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import AVFoundation

// MARK: - Input & Output protocols
protocol DiscountCardCreateRouterInput {
    func navigateToBarcodeReader()
}

class DiscountCardCreateRouter: DiscountCardCreateRouterInput {
    // MARK: - Properties
    weak var viewController: DiscountCardCreateViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToBarcodeReader() {
        let storyboard = UIStoryboard(name: "DiscountCardCreate", bundle: nil)
        let barcodeReaderVC = storyboard.instantiateViewController(withIdentifier: "BarcodeReaderVC") as! BarcodeReaderViewController
        
        viewController.navigationController?.pushViewController(barcodeReaderVC, animated: true)
        
        // Handler code completion
        barcodeReaderVC.handlerReadBarcodeCompletion = { barcode in
            self.viewController.textFieldsCollection.last!.text = (barcode as! AVMetadataMachineReadableCodeObject).stringValue
            self.viewController.barcodeDidGenerateToShow(withCode: (barcode as! AVMetadataMachineReadableCodeObject).stringValue)
        }
    }
    
    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
