//
//  DiscountCardCreateConfigurator.swift
//  OmnieCommerce
//
//  Created by msm72 on 24.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension DiscountCardCreateViewController: DiscountCardCreatePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension DiscountCardCreateInteractor: DiscountCardCreateViewControllerOutput {
}

extension DiscountCardCreatePresenter: DiscountCardCreateInteractorOutput {
}

class DiscountCardCreateConfigurator {
    // MARK: - Properties
    static let sharedInstance = DiscountCardCreateConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: DiscountCardCreateViewController) {
        let router                  =   DiscountCardCreateRouter()
        router.viewController       =   viewController
        
        let presenter               =   DiscountCardCreatePresenter()
        presenter.viewController    =   viewController
        
        let interactor              =   DiscountCardCreateInteractor()
        interactor.presenter        =   presenter
        
        viewController.interactor   =   interactor
        viewController.router       =   router
    }
}
