//
//  DiscountCardCreatePresenter.swift
//  OmnieCommerce
//
//  Created by msm72 on 24.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol DiscountCardCreatePresenterInput {
    func presentSomething(responseModel: DiscountCardCreateModels.Something.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol DiscountCardCreatePresenterOutput: class {
    func displaySomething(viewModel: DiscountCardCreateModels.Something.ViewModel)
}

class DiscountCardCreatePresenter: DiscountCardCreatePresenterInput {
    // MARK: - Properties
    weak var viewController: DiscountCardCreatePresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(responseModel: DiscountCardCreateModels.Something.ResponseModel) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = DiscountCardCreateModels.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
