//
//  DiscountCardShowRouter.swift
//  OmnieCommerce
//
//  Created by msm72 on 24.05.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol DiscountCardShowRouterInput {
    func navigateToDiscountCardCreateScene(withDiscountCard discountCard: DiscountCard?)
}

class DiscountCardShowRouter: DiscountCardShowRouterInput {
    // MARK: - Properties
    weak var viewController: DiscountCardShowViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToDiscountCardCreateScene(withDiscountCard discountCard: DiscountCard?) {
        let storyboard = UIStoryboard(name: "DiscountCardCreate", bundle: nil)
        let discountCardCreateVC = storyboard.instantiateViewController(withIdentifier: "DiscountCardCreateVC") as! DiscountCardCreateViewController
        discountCardCreateVC.discountCard = discountCard
        
        viewController.navigationController?.pushViewController(discountCardCreateVC, animated: true)
    }

    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
